# Generated by Django 4.1.5 on 2023-05-10 12:52

from django.db import migrations, models
import learn.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Гарчиг', models.CharField(max_length=100)),
                ('Бичлэг', models.FileField(upload_to='learn/%y', validators=[learn.validators.file_size])),
                ('Тайлбар', models.CharField(max_length=300)),
            ],
        ),
    ]
